# Generated by Django 4.2.3 on 2023-07-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoTotal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
