# Generated by Django 4.2.3 on 2023-09-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoTotal', '0004_rating_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='taken_with',
            field=models.CharField(default='', max_length=50),
        ),
    ]
